version: '3'

services:
  consulserver01:
    image: consul:1.10
    container_name: consulserver01
    hostname: consulserver01
    command: ['tail', '-f', '/dev/null']
    volumes:
      - ./servers/server01:/etc/consul.d
    networks:
      consul:
        ipv4_address: 172.22.0.2
  consulserver02:
    image: consul:1.10
    container_name: consulserver02
    hostname: consulserver02
    command: [ 'tail', '-f', '/dev/null' ]
    volumes:
      - ./servers/server02:/etc/consul.d
    networks:
      consul:
        ipv4_address: 172.22.0.3
  consulserver03:
    image: consul:1.10
    container_name: consulserver03
    hostname: consulserver03
    command: [ 'tail', '-f', '/dev/null' ]
    volumes:
      - ./servers/server03:/etc/consul.d
    networks:
      consul:
        ipv4_address: 172.22.0.4
  consulclient01:
    image: consul:1.10
    container_name: consulclient01
    hostname: consulclient01
    command: [ 'tail', '-f', '/dev/null' ]
    volumes:
      - ./clients/consul01:/etc/consul.d
    networks:
      consul:
        ipv4_address: 172.22.0.5
  consulclient02:
    image: consul:1.10
    container_name: consulclient02
    hostname: consulclient02
    command: [ 'tail', '-f', '/dev/null' ]
    volumes:
      - ./clients/consul02:/etc/consul.d
    networks:
      consul:
        ipv4_address: 172.22.0.6

networks:
  consul:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/24
